### ISSUE TITLE
为什么现在不能swap交易了？这么久了，什么时候开放？是跑路了吗？

### ISSUE THREAD

**Issue by dengjihai** [dogexme/swordpool#2]
为什么现在不能swap交易了？这么久了，什么时候开放？是跑路了吗？为什么现在不能swap交易了？这么久了，什么时候开放？是跑路了吗？为什么现在不能swap交易了？这么久了，什么时候开放？是跑路了吗？为什么现在不能swap交易了？这么久了，什么时候开放？是跑路了吗？为什么现在不能swap交易了？这么久了，什么时候开放？是跑路了吗？为什么现在不能swap交易了？这么久了，什么时候开放？是跑路了吗？为什么现在不能swap交易了？这么久了，什么时候开放？是跑路了吗？为什么现在不能swap交易了？这么久了，什么时候开放？是跑路了吗？

**Comment by dogexme** [comment]
ss

**Comment by dengjihai** [comment]
啥？你凭啥关闭我的问题？
