### ISSUE TITLE
为什么能关闭我的问题？不回复？

### ISSUE THREAD

**Issue by dengjihai** [dogexme/swordpool#5]
为什么能关闭我的问题？不回复？

_Originally posted by @dengjihai in https://github.com/dogexme/swordpool/issues/1#issuecomment-2069021525_

**Comment by dogexme** [comment]
这不是我们发的币，我们不是项目方，你被Kol骗了，认为我们有义务一直运维这个swap。
我们甚至没有公开宣传过我们的东西，我们一开始只想把这个当作是一种测试实验性的产品，以便为未来的产品做测试，但是被人盯上进行炒作。
我们很早在社区内说过不会一直运营，本来是打算交给第三方不停机运营的，但是后面基本没有交易量而且我们被攻击导致无法运营，这是没有办法的事情。你可以去小交易所或者其他支持的otc交易。
